// ================================
// Copyright (c) 2025 reall3d.com
// ================================
export const VarCurrentVisibleRadius = 'currentVisibleRadius';
export const VarCurrentLightRadius = 'currentLightRadius';
export const VarRealFocusPosition = 'realFocusPosition';
export const VarNdcFocusPosition = 'ndcFocusPosition';
export const VarSplatShTexture12 = 'splatShTexture12';
export const VarSplatShTexture3 = 'splatShTexture3';
export const VarPerformanceNow = 'performanceNow';
export const VarWaterMarkColor = 'waterMarkColor';
export const VarShowWaterMark = 'showWaterMark';
export const VarSplatTexture0 = 'splatTexture0';
export const VarSplatTexture1 = 'splatTexture1';
export const VarBigSceneMode = 'bigSceneMode';
export const VarLightFactor = 'lightFactor';
export const VarNdcPosition = 'ndcPosition';
export const VarDebugEffect = 'debugEffect';
export const VarUsingIndex = 'usingIndex';
export const VarCycleColor = 'cycleColor';
export const VarSplatIndex = 'splatIndex';
export const VarVPosition = 'vPosition';
export const VarNdcCenter = 'ndcCenter';
export const VarPointMode = 'pointMode';
export const VarMarkPoint = 'markPoint';
export const VarShDegree = 'shDegree';
export const VarViewport = 'viewport';
export const VarCenState = 'cenState';
export const VarOpacity = 'opacity';
export const VarVColor = 'vColor';
export const VarVAngle = 'vAngle';
export const VarFocal = 'focal';
export const VarTopY = 'topY';
